### ISSUE TITLE
Can throw when creating alert

### ISSUE THREAD

**Issue by STRML** [BitMEX/graylog-plugin-slack#1]
```
java.lang.NullPointerException: null value in entry: title=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[graylog.jar:?]
	at org.graylog2.alerts.AbstractAlertCondition.getPersistedFields(AbstractAlertCondition.java:143) ~[graylog.jar:?]
	at org.graylog2.database.PersistedServiceImpl.embed(PersistedServiceImpl.java:255) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.addAlertCondition(StreamServiceImpl.java:316) ~[graylog.jar:?]
	at org.graylog2.rest.resources.streams.StreamResource.cloneStream(StreamResource.java:439) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]

```

**Comment by jinmingshao** [comment]
This happens when copying the existing alert conditions which are missing `title`.
It used to have `Manage Alerts` per Stream where we added Alert Conditions without `title`; Now looks like Alert Condition is separate and requires `title`.
I will recreate those Alert Conditions with correct titles.
